//
//  PXStrings.swift
//  MercadoPagoSDK

import Foundation

enum PXStrings {
    static let error_body_title_ = "error_body_title_"
    static let error_body_description_ = "error_body_description_"
    static let error_body_description_pending_contingency = "error_body_description_pending_contingency"
    static let error_body_description_pending_review_manual = "error_body_description_pending_review_manual"
    static let error_body_description_cc_rejected_call_for_authorize = "error_body_description_cc_rejected_call_for_authorize"
    static let error_body_description_cc_rejected_card_disabled = "error_body_description_cc_rejected_card_disabled"
    static let error_body_description_cc_rejected_insufficient_amount = "error_body_description_cc_rejected_insufficient_amount"
    static let error_body_description_cc_rejected_other_reason = "error_body_description_cc_rejected_other_reason"
    static let error_body_description_rejected_by_bank = "error_body_description_rejected_by_bank"
    static let error_body_description_rejected_insufficient_data = "error_body_description_rejected_insufficient_data"
    static let error_body_description_cc_rejected_duplicated_payment = "error_body_description_cc_rejected_duplicated_payment"
    static let error_body_description_cc_rejected_max_attempts = "error_body_description_cc_rejected_max_attempts"
    static let error_body_description_rejected_high_risk = "error_body_description_rejected_high_risk"
    static let error_body_action_text_ = "error_body_action_text_"
    static let error_body_action_text_cc_rejected_call_for_authorize = "error_body_action_text_cc_rejected_call_for_authorize"
    static let error_body_secondary_title_ = "error_body_secondary_title_"
    static let discount_coupon_detail_default_concept = "discount_coupon_detail_default_concept"
    static let discount_coupon_detail_description = "discount_coupon_detail_description"
    static let payment_result_screen_congrats_finish_button = "payment_result_screen_congrats_finish_button"
    static let card_form_next_button = "card_form_next_button"
    static let card_form_previous_button = "card_form_previous_button"
    static let card_form_card_number = "card_form_card_number"
    static let card_form_expiration_date = "card_form_expiration_date"
    static let card_form_security_code = "card_form_security_code"
    static let card_form_name_and_surname = "card_form_name_and_surname"
    static let card_form_name_surname = "card_form_name_surname"
    static let card_form_month_year = "card_form_month_year"
    static let card_form_show_promotions = "card_form_show_promotions"
    static let card_form_invalid_field = "card_form_invalid_field"
    static let card_form_invalid_cvv_length = "card_form_invalid_cvv_length"
    static let card_form_invalid_card_length = "card_form_invalid_card_length"
    static let card_form_invalid_card_length_general = "card_form_invalid_card_length_general"
    static let card_form_card_not_supported = "card_form_card_not_supported"
    static let identification_form_id_number = "identification_form_id_number"
    static let payer_info_name = "payer_info_name"
    static let payer_info_surname = "payer_info_surname"
    static let payer_info_number = "payer_info_number"
    static let payer_info_type = "payer_info_type"
    static let review_change_payment_method_action = "review_change_payment_method_action"
    static let review_title = "review_title"
    static let confirm_action = "confirm_action"
    static let cancel_action = "cancel_action"
    static let exit_action = "exit_action"
    static let retry_action = "retry_action"
    static let yes_string = "yes_string"
    static let no_string = "no_string"
    static let error_title = "error_title"
    static let success_payment_title = "success_payment_title"
    static let cancel_payment_action = "cancel_payment_action"
    static let unit_price_string = "unit_price_string"
    static let quantity_string = "quantity_string"
    static let payment_method_not_supported = "payment_method_not_supported"
    static let more_information = "more_information"
    static let additional_step_issuer_selection_title = "additional_step_issuer_selection_title"
    static let additional_step_card_type_title = "additional_step_card_type_title"
    static let additional_step_entity_type_title = "additional_step_entity_type_title"
    static let additional_step_financial_institution_title = "additional_step_financial_institution_title"
    static let card_type_credit_option = "card_type_credit_option"
    static let card_type_debit_option = "card_type_debit_option"
}
